version: '3'
services:
    mongo:
        container_name: mongo-container
        image: mongo:3
        restart: always
        ports:
            - '27017:27017'
    api:
        container_name: api-container
        image: node:15
        working_dir: /usr/src/typescript-mongoose-inversify-ms-api
        restart: always
        command: bash -c "npm install --only=prod --force && npm start"
        volumes:
            - ./dist:/usr/src/typescript-mongoose-inversify-ms-api/dist
            - ./package.json:/usr/src/typescript-mongoose-inversify-ms-api/package.json
        ports:
            - '3000:3000'
        links:
            - mongo
